[build]
  base = "testwebsite"        # Netlify installs dependencies here and runs the build command
  publish = "testwebsite"     # This is the folder where your built files should be published
  functions = "testwebsite/netlify/functions"  # Where your serverless functions live

  # If you have a custom build command, specify it here
  command = "npm run build"  # Or whatever command you use to build your project

[dev]
  functions = "testwebsite/netlify/functions"


[[redirects]]
  from = "/*"                # Redirect all routes to index.html for React Router
  to = "/index.html"         # Rewrite them to index.html
  status = 200               # Status code is 200 for the rewrite (not a redirect)
  force = true               # Forces the rewrite even if the path exists


