[build]
  publish = "build"          # Netlify will look for your built React app in this folder
  command = "npm run build"  # The build command for React (or use yarn if applicable)

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"  # Caching headers for assets
