[build]
  base = "/"
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "16.x"

[functions]
  directory = "netlify/functions"

[context.production.environment]
  NODE_ENV = "production"
