name: React App CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Specify Node.js version (or latest LTS)

    - name: Install dependencies
      run: |
        npm install

    - name: Run tests
      run: |
        npm test -- --watchAll=false

    - name: Build React app
      run: |
        npm run build

    - name: Upload build artifacts (optional, for deployment)
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: build/

# Deployment step (if you want to deploy to a platform like Netlify, Vercel, or AWS)
deploy:
  runs-on: ubuntu-latest
  needs: build  # Ensure the build job is successful before deployment

  steps:
  - name: Check out the repository
    uses: actions/checkout@v3

  - name: Deploy to [your deploy platform]
    run: |
      # Example: Deploy to Netlify or another platform
      # For example, if you're using Netlify:
      curl -sL https://github.com/netlify/actions/releases/download/v1.0.0/netlify-action.tar.gz | tar xz -C /tmp
      /tmp/netlify-action/netlify deploy --site-id ${{ secrets.NETLIFY_SITE_ID }} --auth ${{ secrets.NETLIFY_AUTH_TOKEN }} --dir build/
