name: React CI

on:
  pull_request:
  workflow_dispatch:name: React CI

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - create-deployed-test

jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test

  push:
    branches: [ create-deployed-test ]

jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        uses: actions/setup-node@v2
      - name: Set up Node.js

        with:
          node-version: '20'

      - run: npm install
      - run: npm run test    

