name: React CI

on:
  pull_request: [ create-deployed-test ]
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run Tests
        run: |
          for i in {1..3}; do
            npm run test && break || sleep 10
          done
